// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-preferences'
  | 'menu-read-aloud'
  | 'menu-stop-reading'
  | 'menuitem-read-aloud'
  | 'menuitem-stop-reading'
  | 'pref-help'
  | 'pref-python-path-label'
  | 'pref-rate-label'
  | 'pref-test-voice'
  | 'pref-title'
  | 'pref-voice-label'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tts-error'
  | 'tts-finished'
  | 'tts-generating'
  | 'tts-no-text'
  | 'tts-playing';
